### ISSUE TITLE
SCORM Export 

### ISSUE THREAD

**Issue by MichaelR28** [Smart-Study-Graz/SmartAuthoring#3]
**Describe the bug**
When Exporting a SCORM course an error appears and it fails.

**To Reproduce**
1. Go to /main/courses/course?id=2
2. Click on Export Course 
3. See error

![image](https://user-images.githubusercontent.com/53524867/204471840-7ef68e54-3037-468a-9a12-089cc7c8af01.png)

**Comment by Hafnernuss** [comment]
This only occurs if you have not edited any slides. However, it's still a bug and will be fixed in the next release.
